### ISSUE TITLE
Fix tutorial

### ISSUE THREAD

**Issue by thecardkid** [kyflores/CA16_tools#1]
- Add instructions for retrieving Extensionpack. Also note that `sudo apt-get install virtualbox` on ubuntu 14.04 installs version 4.3.36. Older versions can be found at https://www.virtualbox.org/wiki/Download_Old_Builds
- After adding yourself to `vboxusers` (add command for that), must log out then back in
- Add warning that `vagrant up` will first show percentages, but then go dark until it completes. 
- I'd suggest removing the `vagrant destroy` part. Or put it in a very clearly separate section. Replace this line with suggesting that reader should delete CA16.box
- Add notes about clicking the correct button when messages pop up in VM. Also note that reader must cd into `/vagrant/` not `/[something]/vagrant/`

That's all I can think of for now

**Comment by kyflores** [comment]
Changed in readme, except that I left vagrant destroy in and made a not that it is really for purging files from the computer completely.
